### ISSUE TITLE
Fishing Rod broken when using this Mod.

### ISSUE THREAD

**Issue by HalfdeadKiller** [AmyMialee/black-powder-fabric#2]
With only Black Powder, Cloth Config API, and Frabric API the fishing rod fails to cast the bobber. Once the mod is removed the fishing rod functions as expected.

[latest.log](https://github.com/AmyMialee/black-powder-fabric/files/7125485/latest.log)

**Comment by AmyMialee** [comment]
Issue with multi-item-lib that can't be fixed until the lib updates.

**Comment by spunkiethefirst** [comment]
I have also experienced the fishing rod mallfunction, additionally I am experiencing an error with shearing sheep, snow golems, and bee hives. Just like HalfdeadKiller, removing the "black-powder-1.0.6.jar" from the mods folder restores their function.

**Comment by AmyMialee** [comment]
Same issue with same solution

**Comment by AmyMialee** [comment]
https://github.com/OroArmor/Multi-Item-Lib/issues/7
