### ISSUE TITLE
 Black Powder seems to be incompatible with BCLib 

### ISSUE THREAD

**Issue by JTBWatchDog** [AmyMialee/black-powder-fabric#4]
I'm not entirely sure why, but Black Powder seems to be incompatible with Fabric 1.17.1 BCLib, from version 0.4.2 to 0.5.5. Found this issue while trying to add Black Powder to a modpack I'm building, systematically removed and readded mods until I found the conflict. Log of attempting to run Black Powder 1.0.6 with BCLib 0.5.5 attached.
[latest.log](https://github.com/AmyMialee/black-powder-fabric/files/7697872/latest.log)

**Comment by AmyMialee** [comment]
Yea this is another Multi-Item-Lib issue, This won't be fixed till the overhaul which is a long while off sorry.

**Comment by AmyMialee** [comment]
And it'll only be for 1.18 when I do make it.

**Comment by JTBWatchDog** [comment]
Alright, thank you.
